---
- name: Pull Docker image of Calculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python2.7
  tasks:
    - name: Pull image
      docker_image:
        name: parvparikh/calc:latest
        source: pull
    - name: Start docker service
      service: 
        name: docker
        state: started
    - name: Running container
      shell: docker run -it -d --name calc parvparikh/calc
        
